timeout 9999
start:

send ""

expect {
    "Oclea login:"
}
send root
sleep 3
send clear
send ""

expect {
	"[root@Oclea ~]#"
}
send ""
send oclea_bootstrap imx327
expect {
	"[root@Oclea ~]#"
}
send hydra_provision -i 0 -s 0x0101 0x0103 -s 0x0401 0x0780 -s 0x0402 0x0438 -s 0x0403 0x001e -s 0x0103 0x0101
expect {
	"[root@Oclea ~]#"
}
send ""
send hydra
expect {
	"[root@Oclea ~]#"
}
send oclea_gstreamer_interactive_example -r

expect {
	">>>"
}

goto start
